<a href="https://colab.research.google.com/github/tjp1992/ML-Jupyter/blob/main/Projects/05_Training_Models_Oreilly/Training_Model_Note.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Training Model

The Following Notebook is intended for study purposes only, the following file contains notes and follow up codes from [Hands on Machine Learning with Scikit-Learn and Tensorflow](https://www.amazon.com/s?k=hands+on+machine+learning+with+scikit-learn+and+tensorflow&sprefix=hands+on+ma%2Caps%2C326&ref=nb_sb_ss_ts-doa-p_4_11).



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
X = 2 * np.random.rand(100,1)
y = 4 + 3 * X + np.random.randn(100, 1)

X_b = np.c_[np.ones((100,1)), X] # add x0 = 1 to each instance
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

theta_best

array([[3.91264021],
       [3.05597741]])

In [4]:
X_new = np.array([[0],[2]])
X_new_b = np.c_[np.ones((2,1)), X_new]
y_predict = X_new_b.dot(theta_best)
y_predict

array([[ 3.91264021],
       [10.02459503]])

In [ ]:
plt.figure(figsize= (15,12))
plt.plot(X_new, y_predict, 'r-')
plt.plot(X, y, "b.")
plt.axis([0,2,0,15])
plt.show()

In [9]:
eta = 0.1
n_iterations = 1000
m = 100

theta = np.random.randn(2,1)

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta)-y)
    theta = theta - eta * gradients

theta

array([[3.91264021],
       [3.05597741]])